
title: My Resume
url: 'https://puricamaykol.github.io'
baseurl: '/cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Maykol Purica
tagline: Full Stack Web Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: puricamaykol@gmail.com
phone: +58424281702
website: puricamaykol.github.io #do not add http://
linkedin: puricamaykol
github: puricamaykol

#Update all the sections by editing the files inside _includes folder.
